title: Modestly Mindful
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.5
  rhythmicContrast: 0.75
  brandColors:
    - '#73a3af'
    - '#ffffff'
    - '#808080'
    - '#00ffff'
    - '#ccdee2'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Modestly Mindful
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06902985
layout_spectrum: 1
