name: Modestly Mindful
favicon: null
layout_spectrum: 0.37083
typography_spectrum: 0.6957
title: Modestly Mindful
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73a3af'
    - '#ffffff'
    - '#808080'
    - '#00ffff'
    - '#ccdee2'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
